#Minecraft server properties
#Wed Feb 04 21:30:06 UTC 2026
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=false
debug=false
difficulty=easy
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=50
max-tick-time=60000
max-world-size=29999984
motd=t.me/furyworlds
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25510
rate-limit=0
rcon.password=gamemodeigoridze
rcon.port=30015
resource-pack=https\://www.dropbox.com/scl/fi/154r2ev71e1mkwoo1imd1/furyworlds.t.me.zip?rlkey\=o9906sp35sw4k0t1b7kjrd3dh&st\=rgfbh98s&dl\=1
resource-pack-sha1=b7a12731a60416692b6fbecc9723d4617079ed42
server-ip=0.0.0.0
server-name=rw2
server-port=30002
simulation-distance=16
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=16
white-list=false
